---
title: "US Plants Digitization Status"
author: "Jocelyn Pender"
date: "10/07/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.width=12, fig.height=6) 

```

## R Markdown


```{r cars}
library(MASS) # provides the parcoord() function that automatically builds parallel coordinates chart
library(tidyverse)
library(GGally)
```

```{r data_prep}
gbif_us_dataset <- read_csv("../gbif_institutionCode_summmary/gbif_us_institutionCode_MIDS_2020.07.08.csv")

# Sort columns based on MIDS level
gbif_us_dataset <- gbif_us_dataset %>% relocate(has_collectionCode, has_catalogNumber, has_countryCode, has_higherGeography, has_locality, has_eventDate, has_dateIdentified, has_identifiedBy, has_recordedBy, has_image, has_coordinates, has_speciesKey)
  
# Filter dataset for easier viewing
top_5_gbif_us_dataset <- gbif_us_dataset %>% top_n(5, total)
bottom_5_gbif_us_dataset <- gbif_us_dataset %>% top_n(-5, total)

# Generate percentage of totals as data
percentage_gbif_us_dataset <- gbif_us_dataset[, 1:12] %>%
  mutate(across(everything()), . / gbif_us_dataset$total) 

```


```{r mass_parcoord_plot, echo=FALSE}
generate_mass_parcoord_plot <- function(gbif_us_dataset, percentage_gbif_us_dataset) {
  # Vector color
  numeric_institutions <- gbif_us_dataset$institutionCode %>% as.factor() %>% as.numeric()
  my_colors <- colors()[numeric_institutions*11]
  
  # Make the graph !
  parcoord(percentage_gbif_us_dataset, col = my_colors)
}

mass_parcoord_plot <- generate_mass_parcoord_plot(gbif_us_dataset, percentage_gbif_us_dataset)
mass_parcoord_plot

```


```{r}

generate_ggally_parcoord_plot <- function(gbif_us_dataset) {
  # Sort columns based on MIDS level
  gbif_us_dataset <- gbif_us_dataset %>% relocate(has_collectionCode, has_catalogNumber, has_countryCode, has_higherGeography, has_locality, has_eventDate, has_dateIdentified, has_identifiedBy, has_recordedBy, has_image, has_coordinates, has_speciesKey)
    
  # Generate percentage of totals as data
  percentage_gbif_us_dataset <- gbif_us_dataset[, 1:12] %>%
    mutate(across(everything()), . / gbif_us_dataset$total) 
  
  # add back in the institutionCode
  percentage_gbif_us_dataset <- cbind(percentage_gbif_us_dataset, gbif_us_dataset$institutionCode)
  colnames(percentage_gbif_us_dataset)[13] <- "institutionCode"
  parcordd_plot <- ggparcoord(data = percentage_gbif_us_dataset, columns = 1:12, groupColumn = 13)
  return(parcordd_plot)
}

ggally_parcordd_plot <- generate_ggally_parcoord_plot(gbif_us_dataset)
ggally_parcordd_plot
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
